/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CowInput = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'ageMonths' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'milkCapacityLiters' : IDL.Nat,
  'healthStatus' : IDL.Text,
  'breed' : IDL.Text,
  'price' : IDL.Nat,
});
export const CowId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Cow = IDL.Record({
  'id' : CowId,
  'imageUrls' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'ageMonths' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'milkCapacityLiters' : IDL.Nat,
  'healthStatus' : IDL.Text,
  'breed' : IDL.Text,
  'price' : IDL.Nat,
});
export const ProductCategory = IDL.Variant({
  'Cow' : IDL.Null,
  'Milk' : IDL.Null,
  'DairyProduct' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const Stats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'pendingEnquiries' : IDL.Nat,
});
export const EnquiryId = IDL.Nat;
export const EnquiryStatus = IDL.Variant({
  'New' : IDL.Null,
  'Read' : IDL.Null,
  'Replied' : IDL.Null,
});
export const EnquiryType = IDL.Variant({
  'ProductQuestion' : IDL.Null,
  'General' : IDL.Null,
  'CowInquiry' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'id' : EnquiryId,
  'customerName' : IDL.Text,
  'status' : EnquiryStatus,
  'subject' : IDL.Text,
  'customerPhone' : IDL.Text,
  'enquiryType' : EnquiryType,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'customerEmail' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'CashOnDelivery' : IDL.Null,
});
export const OrderType = IDL.Variant({
  'OneTime' : IDL.Null,
  'SubscriptionWeekly' : IDL.Null,
  'SubscriptionDaily' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'specialInstructions' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const Settings = IDL.Record({
  'deliveryPolicy' : IDL.Text,
  'whatsappGreeting' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'contactEmail' : IDL.Text,
  'businessPhone' : IDL.Text,
  'hoursOfOperation' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'orderType' : OrderType,
  'specialInstructions' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const EnquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'subject' : IDL.Text,
  'customerPhone' : IDL.Text,
  'enquiryType' : EnquiryType,
  'message' : IDL.Text,
  'customerEmail' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCow' : IDL.Func([CowInput], [Cow], []),
  'addProduct' : IDL.Func([ProductInput], [Product], []),
  'checkIsAdmin' : IDL.Func([], [IDL.Bool], []),
  'deleteCow' : IDL.Func([CowId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAvailableCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
  'getCowById' : IDL.Func([CowId], [IDL.Opt(Cow)], ['query']),
  'getCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
  'getDashboardStats' : IDL.Func([], [Stats], []),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'placeOrder' : IDL.Func([OrderInput], [Order], []),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
  'submitEnquiry' : IDL.Func([EnquiryInput], [Enquiry], []),
  'toggleCowAvailability' : IDL.Func([CowId], [IDL.Opt(Cow)], []),
  'toggleProductActive' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
  'updateCow' : IDL.Func([CowId, CowInput], [IDL.Opt(Cow)], []),
  'updateEnquiryStatus' : IDL.Func(
      [EnquiryId, EnquiryStatus],
      [IDL.Opt(Enquiry)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Opt(Product)], []),
  'updateSettings' : IDL.Func([Settings], [Settings], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CowInput = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'ageMonths' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'milkCapacityLiters' : IDL.Nat,
    'healthStatus' : IDL.Text,
    'breed' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CowId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Cow = IDL.Record({
    'id' : CowId,
    'imageUrls' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'ageMonths' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'milkCapacityLiters' : IDL.Nat,
    'healthStatus' : IDL.Text,
    'breed' : IDL.Text,
    'price' : IDL.Nat,
  });
  const ProductCategory = IDL.Variant({
    'Cow' : IDL.Null,
    'Milk' : IDL.Null,
    'DairyProduct' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const Stats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'pendingEnquiries' : IDL.Nat,
  });
  const EnquiryId = IDL.Nat;
  const EnquiryStatus = IDL.Variant({
    'New' : IDL.Null,
    'Read' : IDL.Null,
    'Replied' : IDL.Null,
  });
  const EnquiryType = IDL.Variant({
    'ProductQuestion' : IDL.Null,
    'General' : IDL.Null,
    'CowInquiry' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'id' : EnquiryId,
    'customerName' : IDL.Text,
    'status' : EnquiryStatus,
    'subject' : IDL.Text,
    'customerPhone' : IDL.Text,
    'enquiryType' : EnquiryType,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'customerEmail' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'UPI' : IDL.Null,
    'CashOnDelivery' : IDL.Null,
  });
  const OrderType = IDL.Variant({
    'OneTime' : IDL.Null,
    'SubscriptionWeekly' : IDL.Null,
    'SubscriptionDaily' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'createdAt' : Timestamp,
    'orderType' : OrderType,
    'specialInstructions' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const Settings = IDL.Record({
    'deliveryPolicy' : IDL.Text,
    'whatsappGreeting' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'contactEmail' : IDL.Text,
    'businessPhone' : IDL.Text,
    'hoursOfOperation' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'orderType' : OrderType,
    'specialInstructions' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const EnquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'subject' : IDL.Text,
    'customerPhone' : IDL.Text,
    'enquiryType' : EnquiryType,
    'message' : IDL.Text,
    'customerEmail' : IDL.Text,
  });
  
  return IDL.Service({
    'addCow' : IDL.Func([CowInput], [Cow], []),
    'addProduct' : IDL.Func([ProductInput], [Product], []),
    'checkIsAdmin' : IDL.Func([], [IDL.Bool], []),
    'deleteCow' : IDL.Func([CowId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getAdmin' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAvailableCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
    'getCowById' : IDL.Func([CowId], [IDL.Opt(Cow)], ['query']),
    'getCows' : IDL.Func([], [IDL.Vec(Cow)], ['query']),
    'getDashboardStats' : IDL.Func([], [Stats], []),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'placeOrder' : IDL.Func([OrderInput], [Order], []),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
    'submitEnquiry' : IDL.Func([EnquiryInput], [Enquiry], []),
    'toggleCowAvailability' : IDL.Func([CowId], [IDL.Opt(Cow)], []),
    'toggleProductActive' : IDL.Func([ProductId], [IDL.Opt(Product)], []),
    'updateCow' : IDL.Func([CowId, CowInput], [IDL.Opt(Cow)], []),
    'updateEnquiryStatus' : IDL.Func(
        [EnquiryId, EnquiryStatus],
        [IDL.Opt(Enquiry)],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, ProductInput],
        [IDL.Opt(Product)],
        [],
      ),
    'updateSettings' : IDL.Func([Settings], [Settings], []),
  });
};

export const init = ({ IDL }) => { return []; };