/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cow {
  'id' : CowId,
  'imageUrls' : Array<string>,
  'createdAt' : Timestamp,
  'ageMonths' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'milkCapacityLiters' : bigint,
  'healthStatus' : string,
  'breed' : string,
  'price' : bigint,
}
export type CowId = bigint;
export interface CowInput {
  'imageUrls' : Array<string>,
  'ageMonths' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'milkCapacityLiters' : bigint,
  'healthStatus' : string,
  'breed' : string,
  'price' : bigint,
}
export interface Enquiry {
  'id' : EnquiryId,
  'customerName' : string,
  'status' : EnquiryStatus,
  'subject' : string,
  'customerPhone' : string,
  'enquiryType' : EnquiryType,
  'createdAt' : Timestamp,
  'message' : string,
  'customerEmail' : string,
}
export type EnquiryId = bigint;
export interface EnquiryInput {
  'customerName' : string,
  'subject' : string,
  'customerPhone' : string,
  'enquiryType' : EnquiryType,
  'message' : string,
  'customerEmail' : string,
}
export type EnquiryStatus = { 'New' : null } |
  { 'Read' : null } |
  { 'Replied' : null };
export type EnquiryType = { 'ProductQuestion' : null } |
  { 'General' : null } |
  { 'CowInquiry' : null };
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'specialInstructions' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export type OrderId = bigint;
export interface OrderInput {
  'customerName' : string,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'orderType' : OrderType,
  'specialInstructions' : string,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Cancelled' : null } |
  { 'Pending' : null };
export type OrderType = { 'OneTime' : null } |
  { 'SubscriptionWeekly' : null } |
  { 'SubscriptionDaily' : null };
export type PaymentMethod = { 'UPI' : null } |
  { 'CashOnDelivery' : null };
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'Cow' : null } |
  { 'Milk' : null } |
  { 'DairyProduct' : null };
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export interface Settings {
  'deliveryPolicy' : string,
  'whatsappGreeting' : string,
  'whatsappNumber' : string,
  'contactEmail' : string,
  'businessPhone' : string,
  'hoursOfOperation' : string,
}
export interface Stats {
  'totalOrders' : bigint,
  'pendingOrders' : bigint,
  'totalRevenue' : bigint,
  'pendingEnquiries' : bigint,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addCow' : ActorMethod<[CowInput], Cow>,
  'addProduct' : ActorMethod<[ProductInput], Product>,
  'checkIsAdmin' : ActorMethod<[], boolean>,
  'deleteCow' : ActorMethod<[CowId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getAdmin' : ActorMethod<[], [] | [Principal]>,
  'getAvailableCows' : ActorMethod<[], Array<Cow>>,
  'getCowById' : ActorMethod<[CowId], [] | [Cow]>,
  'getCows' : ActorMethod<[], Array<Cow>>,
  'getDashboardStats' : ActorMethod<[], Stats>,
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getSettings' : ActorMethod<[], Settings>,
  'placeOrder' : ActorMethod<[OrderInput], Order>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
  'submitEnquiry' : ActorMethod<[EnquiryInput], Enquiry>,
  'toggleCowAvailability' : ActorMethod<[CowId], [] | [Cow]>,
  'toggleProductActive' : ActorMethod<[ProductId], [] | [Product]>,
  'updateCow' : ActorMethod<[CowId, CowInput], [] | [Cow]>,
  'updateEnquiryStatus' : ActorMethod<
    [EnquiryId, EnquiryStatus],
    [] | [Enquiry]
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<[ProductId, ProductInput], [] | [Product]>,
  'updateSettings' : ActorMethod<[Settings], Settings>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];