/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EnquiryId = bigint;
export interface ProductInput {
    name: string;
    description: string;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: ProductCategory;
    price: bigint;
}
export type Timestamp = bigint;
export interface EnquiryInput {
    customerName: string;
    subject: string;
    customerPhone: string;
    enquiryType: EnquiryType;
    message: string;
    customerEmail: string;
}
export interface CowInput {
    imageUrls: Array<string>;
    ageMonths: bigint;
    isAvailable: boolean;
    description: string;
    milkCapacityLiters: bigint;
    healthStatus: string;
    breed: string;
    price: bigint;
}
export interface OrderItem {
    productId: ProductId;
    quantity: bigint;
    price: bigint;
}
export interface Stats {
    totalOrders: bigint;
    pendingOrders: bigint;
    totalRevenue: bigint;
    pendingEnquiries: bigint;
}
export interface OrderInput {
    customerName: string;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    orderType: OrderType;
    specialInstructions: string;
    totalAmount: bigint;
    items: Array<OrderItem>;
    customerEmail: string;
}
export interface Enquiry {
    id: EnquiryId;
    customerName: string;
    status: EnquiryStatus;
    subject: string;
    customerPhone: string;
    enquiryType: EnquiryType;
    createdAt: Timestamp;
    message: string;
    customerEmail: string;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: Timestamp;
    orderType: OrderType;
    specialInstructions: string;
    totalAmount: bigint;
    items: Array<OrderItem>;
    customerEmail: string;
}
export interface Settings {
    deliveryPolicy: string;
    whatsappGreeting: string;
    whatsappNumber: string;
    contactEmail: string;
    businessPhone: string;
    hoursOfOperation: string;
}
export interface Cow {
    id: CowId;
    imageUrls: Array<string>;
    createdAt: Timestamp;
    ageMonths: bigint;
    isAvailable: boolean;
    description: string;
    milkCapacityLiters: bigint;
    healthStatus: string;
    breed: string;
    price: bigint;
}
export type ProductId = bigint;
export type CowId = bigint;
export type OrderId = bigint;
export interface Product {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: ProductCategory;
    price: bigint;
}
export enum EnquiryStatus {
    New = "New",
    Read = "Read",
    Replied = "Replied"
}
export enum EnquiryType {
    ProductQuestion = "ProductQuestion",
    General = "General",
    CowInquiry = "CowInquiry"
}
export enum OrderStatus {
    Delivered = "Delivered",
    Confirmed = "Confirmed",
    Cancelled = "Cancelled",
    Pending = "Pending"
}
export enum OrderType {
    OneTime = "OneTime",
    SubscriptionWeekly = "SubscriptionWeekly",
    SubscriptionDaily = "SubscriptionDaily"
}
export enum PaymentMethod {
    UPI = "UPI",
    CashOnDelivery = "CashOnDelivery"
}
export enum ProductCategory {
    Cow = "Cow",
    Milk = "Milk",
    DairyProduct = "DairyProduct"
}
export interface backendInterface {
    addCow(input: CowInput): Promise<Cow>;
    addProduct(input: ProductInput): Promise<Product>;
    checkIsAdmin(): Promise<boolean>;
    deleteCow(id: CowId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getAdmin(): Promise<Principal | null>;
    getAvailableCows(): Promise<Array<Cow>>;
    getCowById(id: CowId): Promise<Cow | null>;
    getCows(): Promise<Array<Cow>>;
    getDashboardStats(): Promise<Stats>;
    getEnquiries(): Promise<Array<Enquiry>>;
    getOrderById(id: OrderId): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getProductById(id: ProductId): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getSettings(): Promise<Settings>;
    placeOrder(input: OrderInput): Promise<Order>;
    setAdmin(principal: Principal): Promise<void>;
    submitEnquiry(input: EnquiryInput): Promise<Enquiry>;
    toggleCowAvailability(id: CowId): Promise<Cow | null>;
    toggleProductActive(id: ProductId): Promise<Product | null>;
    updateCow(id: CowId, input: CowInput): Promise<Cow | null>;
    updateEnquiryStatus(id: EnquiryId, status: EnquiryStatus): Promise<Enquiry | null>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
    updateProduct(id: ProductId, input: ProductInput): Promise<Product | null>;
    updateSettings(settings: Settings): Promise<Settings>;
}
import type { Cow as _Cow, Enquiry as _Enquiry, EnquiryId as _EnquiryId, EnquiryInput as _EnquiryInput, EnquiryStatus as _EnquiryStatus, EnquiryType as _EnquiryType, Order as _Order, OrderId as _OrderId, OrderInput as _OrderInput, OrderItem as _OrderItem, OrderStatus as _OrderStatus, OrderType as _OrderType, PaymentMethod as _PaymentMethod, Product as _Product, ProductCategory as _ProductCategory, ProductId as _ProductId, ProductInput as _ProductInput, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCow(arg0: CowInput): Promise<Cow> {
        if (this.processError) {
            try {
                const result = await this.actor.addCow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCow(arg0);
            return result;
        }
    }
    async addProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkIsAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIsAdmin();
            return result;
        }
    }
    async deleteCow(arg0: CowId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCow(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAdmin(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdmin();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdmin();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableCows(): Promise<Array<Cow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableCows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableCows();
            return result;
        }
    }
    async getCowById(arg0: CowId): Promise<Cow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCowById(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCowById(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCows(): Promise<Array<Cow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCows();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCows();
            return result;
        }
    }
    async getDashboardStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiries();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiries();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async placeOrder(arg0: OrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_OrderInput_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_OrderInput_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdmin(arg0);
            return result;
        }
    }
    async submitEnquiry(arg0: EnquiryInput): Promise<Enquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEnquiry(to_candid_EnquiryInput_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Enquiry_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEnquiry(to_candid_EnquiryInput_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Enquiry_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCowAvailability(arg0: CowId): Promise<Cow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCowAvailability(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCowAvailability(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleProductActive(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleProductActive(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleProductActive(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCow(arg0: CowId, arg1: CowInput): Promise<Cow | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCow(arg0, arg1);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCow(arg0, arg1);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEnquiryStatus(arg0: EnquiryId, arg1: EnquiryStatus): Promise<Enquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEnquiryStatus(arg0, to_candid_EnquiryStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEnquiryStatus(arg0, to_candid_EnquiryStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: ProductInput): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: Settings): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
}
function from_candid_EnquiryStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnquiryStatus): EnquiryStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EnquiryType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnquiryType): EnquiryType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Enquiry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enquiry): Enquiry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cow]): Cow | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Enquiry]): Enquiry | null {
    return value.length === 0 ? null : from_candid_Enquiry_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EnquiryId;
    customerName: string;
    status: _EnquiryStatus;
    subject: string;
    customerPhone: string;
    enquiryType: _EnquiryType;
    createdAt: _Timestamp;
    message: string;
    customerEmail: string;
}): {
    id: EnquiryId;
    customerName: string;
    status: EnquiryStatus;
    subject: string;
    customerPhone: string;
    enquiryType: EnquiryType;
    createdAt: Timestamp;
    message: string;
    customerEmail: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_EnquiryStatus_n14(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        customerPhone: value.customerPhone,
        enquiryType: from_candid_EnquiryType_n16(_uploadFile, _downloadFile, value.enquiryType),
        createdAt: value.createdAt,
        message: value.message,
        customerEmail: value.customerEmail
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    deliveryAddress: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    createdAt: _Timestamp;
    orderType: _OrderType;
    specialInstructions: string;
    totalAmount: bigint;
    items: Array<_OrderItem>;
    customerEmail: string;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: Timestamp;
    orderType: OrderType;
    specialInstructions: string;
    totalAmount: bigint;
    items: Array<OrderItem>;
    customerEmail: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n21(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        paymentMethod: from_candid_PaymentMethod_n23(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        orderType: from_candid_OrderType_n25(_uploadFile, _downloadFile, value.orderType),
        specialInstructions: value.specialInstructions,
        totalAmount: value.totalAmount,
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    name: string;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: _ProductCategory;
    price: bigint;
}): {
    id: ProductId;
    name: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: ProductCategory;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: from_candid_ProductCategory_n7(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Read: null;
} | {
    Replied: null;
}): EnquiryStatus {
    return "New" in value ? EnquiryStatus.New : "Read" in value ? EnquiryStatus.Read : "Replied" in value ? EnquiryStatus.Replied : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ProductQuestion: null;
} | {
    General: null;
} | {
    CowInquiry: null;
}): EnquiryType {
    return "ProductQuestion" in value ? EnquiryType.ProductQuestion : "General" in value ? EnquiryType.General : "CowInquiry" in value ? EnquiryType.CowInquiry : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Confirmed" in value ? OrderStatus.Confirmed : "Cancelled" in value ? OrderStatus.Cancelled : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    CashOnDelivery: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "CashOnDelivery" in value ? PaymentMethod.CashOnDelivery : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OneTime: null;
} | {
    SubscriptionWeekly: null;
} | {
    SubscriptionDaily: null;
}): OrderType {
    return "OneTime" in value ? OrderType.OneTime : "SubscriptionWeekly" in value ? OrderType.SubscriptionWeekly : "SubscriptionDaily" in value ? OrderType.SubscriptionDaily : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Cow: null;
} | {
    Milk: null;
} | {
    DairyProduct: null;
}): ProductCategory {
    return "Cow" in value ? ProductCategory.Cow : "Milk" in value ? ProductCategory.Milk : "DairyProduct" in value ? ProductCategory.DairyProduct : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enquiry>): Array<Enquiry> {
    return value.map((x)=>from_candid_Enquiry_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n5(_uploadFile, _downloadFile, x));
}
function to_candid_EnquiryInput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryInput): _EnquiryInput {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_EnquiryStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryStatus): _EnquiryStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_EnquiryType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryType): _EnquiryType {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_OrderInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderInput): _OrderInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: ProductCategory;
    price: bigint;
}): {
    name: string;
    description: string;
    isActive: boolean;
    stock: bigint;
    imageUrl: string;
    category: _ProductCategory;
    price: bigint;
} {
    return {
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        stock: value.stock,
        imageUrl: value.imageUrl,
        category: to_candid_ProductCategory_n3(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    deliveryAddress: string;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    orderType: OrderType;
    specialInstructions: string;
    totalAmount: bigint;
    items: Array<OrderItem>;
    customerEmail: string;
}): {
    customerName: string;
    deliveryAddress: string;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    orderType: _OrderType;
    specialInstructions: string;
    totalAmount: bigint;
    items: Array<_OrderItem>;
    customerEmail: string;
} {
    return {
        customerName: value.customerName,
        deliveryAddress: value.deliveryAddress,
        paymentMethod: to_candid_PaymentMethod_n32(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        orderType: to_candid_OrderType_n34(_uploadFile, _downloadFile, value.orderType),
        specialInstructions: value.specialInstructions,
        totalAmount: value.totalAmount,
        items: value.items,
        customerEmail: value.customerEmail
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    subject: string;
    customerPhone: string;
    enquiryType: EnquiryType;
    message: string;
    customerEmail: string;
}): {
    customerName: string;
    subject: string;
    customerPhone: string;
    enquiryType: _EnquiryType;
    message: string;
    customerEmail: string;
} {
    return {
        customerName: value.customerName,
        subject: value.subject,
        customerPhone: value.customerPhone,
        enquiryType: to_candid_EnquiryType_n38(_uploadFile, _downloadFile, value.enquiryType),
        message: value.message,
        customerEmail: value.customerEmail
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    CashOnDelivery: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.CashOnDelivery ? {
        CashOnDelivery: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    OneTime: null;
} | {
    SubscriptionWeekly: null;
} | {
    SubscriptionDaily: null;
} {
    return value == OrderType.OneTime ? {
        OneTime: null
    } : value == OrderType.SubscriptionWeekly ? {
        SubscriptionWeekly: null
    } : value == OrderType.SubscriptionDaily ? {
        SubscriptionDaily: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryType): {
    ProductQuestion: null;
} | {
    General: null;
} | {
    CowInquiry: null;
} {
    return value == EnquiryType.ProductQuestion ? {
        ProductQuestion: null
    } : value == EnquiryType.General ? {
        General: null
    } : value == EnquiryType.CowInquiry ? {
        CowInquiry: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    Cow: null;
} | {
    Milk: null;
} | {
    DairyProduct: null;
} {
    return value == ProductCategory.Cow ? {
        Cow: null
    } : value == ProductCategory.Milk ? {
        Milk: null
    } : value == ProductCategory.DairyProduct ? {
        DairyProduct: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnquiryStatus): {
    New: null;
} | {
    Read: null;
} | {
    Replied: null;
} {
    return value == EnquiryStatus.New ? {
        New: null
    } : value == EnquiryStatus.Read ? {
        Read: null
    } : value == EnquiryStatus.Replied ? {
        Replied: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Confirmed: null;
} | {
    Cancelled: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Confirmed ? {
        Confirmed: null
    } : value == OrderStatus.Cancelled ? {
        Cancelled: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
